import type { PlatformData } from "./schema";

/**
 * Seed data for the MVP wireframe.
 * Figures are illustrative for demo / Mary validation — not live deal data.
 */
export const platformData: PlatformData = {
  mgas: [
    {
      id: "mga-harborpoint",
      name: "Harborpoint Specialty",
      yearsOfExperience: 28,
      status: "acquired",
      headquarters: "Boston, MA",
      primaryRegion: "Northeast",
      acquiredAt: "2023-06-15",
      notes: "On-platform since 2023. Strong excess casualty book.",
    },
    {
      id: "mga-gulfstream",
      name: "Gulfstream Underwriters",
      yearsOfExperience: 22,
      status: "acquired",
      headquarters: "Tampa, FL",
      primaryRegion: "Southeast",
      acquiredAt: "2024-02-01",
      notes: "Coastal property + flood programs.",
    },
    {
      id: "mga-prairie",
      name: "Prairie Risk Partners",
      yearsOfExperience: 31,
      status: "acquired",
      headquarters: "Chicago, IL",
      primaryRegion: "Midwest",
      acquiredAt: "2024-09-12",
      notes: "Agribusiness and commercial auto.",
    },
    {
      id: "mga-cascade",
      name: "Cascade Binding Co.",
      yearsOfExperience: 19,
      status: "pipeline",
      headquarters: "Seattle, WA",
      primaryRegion: "West",
      notes: "Prospect — strong cyber + tech E&O growth.",
    },
    {
      id: "mga-sunbelt",
      name: "Sunbelt Program Group",
      yearsOfExperience: 26,
      status: "pipeline",
      headquarters: "Dallas, TX",
      primaryRegion: "Southwest",
      notes: "Best-in-class EBITDA growth candidate.",
    },
    {
      id: "mga-atlantic",
      name: "Atlantic Binding Authority",
      yearsOfExperience: 34,
      status: "pipeline",
      headquarters: "Hartford, CT",
      primaryRegion: "Northeast",
      notes: "Deep wholesale relationships; overlapping NE casualty with Harborpoint.",
    },
    {
      id: "mga-ridge",
      name: "Ridge Line MGAs",
      yearsOfExperience: 17,
      status: "pipeline",
      headquarters: "Denver, CO",
      primaryRegion: "Mountain",
      notes: "Below experience threshold — track only.",
    },
    {
      id: "mga-bayou",
      name: "Bayou Specialty Markets",
      yearsOfExperience: 24,
      status: "pipeline",
      headquarters: "New Orleans, LA",
      primaryRegion: "Southeast",
      notes: "Flood + inland marine; synergy with Gulfstream.",
    },
  ],

  financials: [
    // Harborpoint
    { id: "f1", mgaId: "mga-harborpoint", year: 2021, ebitda: 8.2 },
    { id: "f2", mgaId: "mga-harborpoint", year: 2022, ebitda: 9.1 },
    { id: "f3", mgaId: "mga-harborpoint", year: 2023, ebitda: 10.4 },
    { id: "f4", mgaId: "mga-harborpoint", year: 2024, ebitda: 11.8 },
    // Gulfstream
    { id: "f5", mgaId: "mga-gulfstream", year: 2021, ebitda: 5.0 },
    { id: "f6", mgaId: "mga-gulfstream", year: 2022, ebitda: 6.2 },
    { id: "f7", mgaId: "mga-gulfstream", year: 2023, ebitda: 7.5 },
    { id: "f8", mgaId: "mga-gulfstream", year: 2024, ebitda: 9.1 },
    // Prairie
    { id: "f9", mgaId: "mga-prairie", year: 2021, ebitda: 12.0 },
    { id: "f10", mgaId: "mga-prairie", year: 2022, ebitda: 12.4 },
    { id: "f11", mgaId: "mga-prairie", year: 2023, ebitda: 13.1 },
    { id: "f12", mgaId: "mga-prairie", year: 2024, ebitda: 14.0 },
    // Cascade
    { id: "f13", mgaId: "mga-cascade", year: 2021, ebitda: 3.1 },
    { id: "f14", mgaId: "mga-cascade", year: 2022, ebitda: 4.0 },
    { id: "f15", mgaId: "mga-cascade", year: 2023, ebitda: 5.2 },
    { id: "f16", mgaId: "mga-cascade", year: 2024, ebitda: 6.8 },
    // Sunbelt
    { id: "f17", mgaId: "mga-sunbelt", year: 2021, ebitda: 6.5 },
    { id: "f18", mgaId: "mga-sunbelt", year: 2022, ebitda: 8.4 },
    { id: "f19", mgaId: "mga-sunbelt", year: 2023, ebitda: 10.9 },
    { id: "f20", mgaId: "mga-sunbelt", year: 2024, ebitda: 14.2 },
    // Atlantic
    { id: "f21", mgaId: "mga-atlantic", year: 2021, ebitda: 15.0 },
    { id: "f22", mgaId: "mga-atlantic", year: 2022, ebitda: 15.5 },
    { id: "f23", mgaId: "mga-atlantic", year: 2023, ebitda: 16.0 },
    { id: "f24", mgaId: "mga-atlantic", year: 2024, ebitda: 16.4 },
    // Ridge
    { id: "f25", mgaId: "mga-ridge", year: 2022, ebitda: 2.2 },
    { id: "f26", mgaId: "mga-ridge", year: 2023, ebitda: 2.8 },
    { id: "f27", mgaId: "mga-ridge", year: 2024, ebitda: 3.5 },
    // Bayou
    { id: "f28", mgaId: "mga-bayou", year: 2021, ebitda: 4.4 },
    { id: "f29", mgaId: "mga-bayou", year: 2022, ebitda: 5.1 },
    { id: "f30", mgaId: "mga-bayou", year: 2023, ebitda: 6.0 },
    { id: "f31", mgaId: "mga-bayou", year: 2024, ebitda: 7.2 },
  ],

  programs: [
    {
      id: "p1",
      mgaId: "mga-harborpoint",
      name: "NE Excess Casualty",
      lineOfBusiness: "Casualty",
      coverageType: "Excess Liability",
      geographicRegion: "Northeast",
    },
    {
      id: "p2",
      mgaId: "mga-harborpoint",
      name: "Wholesale GL Binding",
      lineOfBusiness: "Casualty",
      coverageType: "General Liability",
      geographicRegion: "Northeast",
    },
    {
      id: "p3",
      mgaId: "mga-gulfstream",
      name: "Coastal Wind Deductible Buyback",
      lineOfBusiness: "Property",
      coverageType: "Wind / Hurricane",
      geographicRegion: "Southeast",
    },
    {
      id: "p4",
      mgaId: "mga-gulfstream",
      name: "Private Flood",
      lineOfBusiness: "Property",
      coverageType: "Flood",
      geographicRegion: "Southeast",
    },
    {
      id: "p5",
      mgaId: "mga-prairie",
      name: "Agribusiness Package",
      lineOfBusiness: "Agriculture",
      coverageType: "Farm Package",
      geographicRegion: "Midwest",
    },
    {
      id: "p6",
      mgaId: "mga-prairie",
      name: "Commercial Auto Fleet",
      lineOfBusiness: "Auto",
      coverageType: "Commercial Auto",
      geographicRegion: "Midwest",
    },
    {
      id: "p6b",
      mgaId: "mga-prairie",
      name: "Midwest Contractor GL",
      lineOfBusiness: "Casualty",
      coverageType: "General Liability",
      geographicRegion: "Midwest",
    },
    {
      id: "p7",
      mgaId: "mga-cascade",
      name: "Tech E&O",
      lineOfBusiness: "Professional Lines",
      coverageType: "Errors & Omissions",
      geographicRegion: "West",
    },
    {
      id: "p8",
      mgaId: "mga-cascade",
      name: "Cyber Affinity",
      lineOfBusiness: "Cyber",
      coverageType: "Cyber Liability",
      geographicRegion: "West",
    },
    {
      id: "p9",
      mgaId: "mga-sunbelt",
      name: "TX Construction GL",
      lineOfBusiness: "Casualty",
      coverageType: "General Liability",
      geographicRegion: "Southwest",
    },
    {
      id: "p10",
      mgaId: "mga-sunbelt",
      name: "Energy Contractors",
      lineOfBusiness: "Casualty",
      coverageType: "Excess Liability",
      geographicRegion: "Southwest",
    },
    {
      id: "p11",
      mgaId: "mga-atlantic",
      name: "NE Wholesale Casualty",
      lineOfBusiness: "Casualty",
      coverageType: "Excess Liability",
      geographicRegion: "Northeast",
    },
    {
      id: "p12",
      mgaId: "mga-atlantic",
      name: "Umbrella Binding",
      lineOfBusiness: "Casualty",
      coverageType: "Umbrella",
      geographicRegion: "Northeast",
    },
    {
      id: "p13",
      mgaId: "mga-ridge",
      name: "Mountain Property",
      lineOfBusiness: "Property",
      coverageType: "Commercial Property",
      geographicRegion: "Mountain",
    },
    {
      id: "p14",
      mgaId: "mga-bayou",
      name: "Gulf Flood Specialty",
      lineOfBusiness: "Property",
      coverageType: "Flood",
      geographicRegion: "Southeast",
    },
    {
      id: "p15",
      mgaId: "mga-bayou",
      name: "Inland Marine Binding",
      lineOfBusiness: "Inland Marine",
      coverageType: "Inland Marine",
      geographicRegion: "Southeast",
    },
  ],

  retailAgencies: [
    {
      id: "r1",
      name: "North Shore Brokers",
      associatedMgaId: "mga-harborpoint",
      city: "Salem",
      state: "MA",
      premiumVolumeMm: 12.4,
    },
    {
      id: "r2",
      name: "Beacon Hill Risk",
      associatedMgaId: "mga-harborpoint",
      city: "Boston",
      state: "MA",
      premiumVolumeMm: 18.1,
    },
    {
      id: "r3",
      name: "Palm Coast Insurance",
      associatedMgaId: "mga-gulfstream",
      city: "Fort Myers",
      state: "FL",
      premiumVolumeMm: 9.7,
    },
    {
      id: "r4",
      name: "Tampa Bay Agency Group",
      associatedMgaId: "mga-gulfstream",
      city: "Tampa",
      state: "FL",
      premiumVolumeMm: 14.2,
    },
    {
      id: "r5",
      name: "Heartland Coverage Co.",
      associatedMgaId: "mga-prairie",
      city: "Des Moines",
      state: "IA",
      premiumVolumeMm: 11.0,
    },
    {
      id: "r6",
      name: "Lakeshore Retail",
      associatedMgaId: "mga-prairie",
      city: "Milwaukee",
      state: "WI",
      premiumVolumeMm: 8.3,
    },
    {
      id: "r7",
      name: "Puget Sound Producers",
      associatedMgaId: "mga-cascade",
      city: "Seattle",
      state: "WA",
      premiumVolumeMm: 7.5,
    },
    {
      id: "r8",
      name: "Lone Star Independent",
      associatedMgaId: "mga-sunbelt",
      city: "Austin",
      state: "TX",
      premiumVolumeMm: 16.8,
    },
    {
      id: "r9",
      name: "Metroplex Risk Partners",
      associatedMgaId: "mga-sunbelt",
      city: "Dallas",
      state: "TX",
      premiumVolumeMm: 22.0,
    },
    {
      id: "r10",
      name: "Constitution State Brokers",
      associatedMgaId: "mga-atlantic",
      city: "Hartford",
      state: "CT",
      premiumVolumeMm: 19.5,
    },
    {
      id: "r11",
      name: "Front Range Agencies",
      associatedMgaId: "mga-ridge",
      city: "Boulder",
      state: "CO",
      premiumVolumeMm: 4.1,
    },
    {
      id: "r12",
      name: "Crescent City Coverage",
      associatedMgaId: "mga-bayou",
      city: "New Orleans",
      state: "LA",
      premiumVolumeMm: 6.9,
    },
  ],
};
