/**
 * Demo dataset for the Newport Specialty Partners platform.
 *
 * Every number here is fabricated, but the set is constructed rather than
 * random so the dashboards can be reasoned about:
 *
 *  - Six MGAs are on platform and eleven are in the pipeline (one passed).
 *  - The pipeline deliberately contains a target that misses each Best in Class
 *    criterion on its own — Great Lakes misses growth by 0.1pt, Palmetto misses
 *    tenure by one year, Front Range misses tenure badly, Old Dominion is flat,
 *    Cardinal is shrinking. Six targets clear all three. That means the filters
 *    on the pipeline screen visibly change the answer instead of always
 *    returning everything.
 *  - Program tags are chosen so the acquired portfolio has real overlap on all
 *    three dimensions, plus capabilities trapped in a single MGA, so the
 *    synergy screen has something true to say.
 *
 * Financial series are declared as EBITDA by year and expanded into revenue and
 * written premium using a per-MGA margin and commission rate, so the three
 * figures stay internally consistent.
 */

import { DEAL_STAGE, MGA_STATUS } from "../src/lib/taxonomy";

/** FY2021 through FY2025 are actuals; FY2026 is a management projection. */
export const FIRST_FISCAL_YEAR = 2021;
export const PROJECTION_FISCAL_YEAR = 2026;
/** Years through which audited statements exist. */
export const AUDITED_THROUGH_YEAR = 2024;

export type ProgramSeed = {
  name: string;
  lineOfBusiness: string;
  coverageType: string;
  geographicRegion: string;
  carrierPartner: string;
  /** Share of the MGA's latest written premium, as a percentage of 100. */
  premiumWeight: number;
  lossRatio: number;
  isActive?: boolean;
};

export type RetailAgencySeed = {
  name: string;
  principalName: string;
  city: string;
  state: string;
  region: string;
  appointedYear: number;
  /** Share of the MGA's latest written premium placed by this retailer. */
  premiumShare: number;
  policyCount: number;
  isActive?: boolean;
};

export type MgaSeed = {
  slug: string;
  name: string;
  status: string;
  stage: string;
  yearsOfExperience: number;
  foundedYear: number;
  principalName: string;
  headquartersCity: string;
  headquartersState: string;
  primaryRegion: string;
  employeeCount: number;
  website: string;
  acquisitionDate?: string;
  enterpriseValueUsd?: number;
  ebitdaMultiple?: number;
  ownershipPercent?: number;
  dealLead: string;
  notes: string;
  /** EBITDA in millions of USD, FY2021 onward. */
  ebitdaMillionsByYear: number[];
  /** Projected FY2026 EBITDA in millions. Omitted where no forecast was shared. */
  projectedEbitdaMillions?: number;
  /** EBITDA / revenue. */
  ebitdaMargin: number;
  /** Revenue / gross written premium — the MGA's blended commission rate. */
  commissionRate: number;
  programs: ProgramSeed[];
  retailAgencies: RetailAgencySeed[];
};

export const MGA_SEEDS: MgaSeed[] = [
  // ---------------------------------------------------------------------------
  // On platform
  // ---------------------------------------------------------------------------
  {
    slug: "harborline-underwriters",
    name: "Harborline Underwriters",
    status: MGA_STATUS.ON_PLATFORM,
    stage: DEAL_STAGE.CLOSED,
    yearsOfExperience: 31,
    foundedYear: 1994,
    principalName: "Ellen Marchetti",
    headquartersCity: "Hartford",
    headquartersState: "CT",
    primaryRegion: "Northeast",
    employeeCount: 84,
    website: "harborlineuw.com",
    acquisitionDate: "2023-06-15",
    enterpriseValueUsd: 62_100_000,
    ebitdaMultiple: 13.5,
    ownershipPercent: 78,
    dealLead: "M. Ruiz",
    notes:
      "First platform acquisition. Ellen has underwritten the same Northeast property book since 1994 and stayed on as platform president. Binding authority on four carriers.",
    ebitdaMillionsByYear: [4.1, 4.6, 5.4, 6.3, 7.4],
    ebitdaMargin: 0.31,
    commissionRate: 0.155,
    programs: [
      {
        name: "Harborline Commercial Property E&S",
        lineOfBusiness: "Commercial Property",
        coverageType: "Excess & Surplus",
        geographicRegion: "Northeast",
        carrierPartner: "Everest Specialty",
        premiumWeight: 34,
        lossRatio: 0.52,
      },
      {
        name: "Northeast Contractors GL",
        lineOfBusiness: "General Liability",
        coverageType: "Admitted Primary",
        geographicRegion: "Northeast",
        carrierPartner: "Trisura Specialty",
        premiumWeight: 26,
        lossRatio: 0.61,
      },
      {
        name: "Mid-Atlantic Property Binding",
        lineOfBusiness: "Commercial Property",
        coverageType: "Excess & Surplus",
        geographicRegion: "Mid-Atlantic",
        carrierPartner: "Clear Blue Specialty",
        premiumWeight: 22,
        lossRatio: 0.49,
      },
      {
        name: "Harborline Umbrella",
        lineOfBusiness: "General Liability",
        coverageType: "Umbrella",
        geographicRegion: "Northeast",
        carrierPartner: "Accredited Specialty",
        premiumWeight: 18,
        lossRatio: 0.44,
      },
    ],
    retailAgencies: [
      {
        name: "Jake Whitmore Insurance Group",
        principalName: "Jake Whitmore",
        city: "Stamford",
        state: "CT",
        region: "Northeast",
        appointedYear: 2011,
        premiumShare: 0.09,
        policyCount: 1840,
      },
      {
        name: "Copley Square Risk Advisors",
        principalName: "Priya Raman",
        city: "Boston",
        state: "MA",
        region: "Northeast",
        appointedYear: 2014,
        premiumShare: 0.08,
        policyCount: 1420,
      },
      {
        name: "Delaware Valley Brokers",
        principalName: "Anthony DiSalvo",
        city: "Wilmington",
        state: "DE",
        region: "Mid-Atlantic",
        appointedYear: 2018,
        premiumShare: 0.07,
        policyCount: 1180,
      },
      {
        name: "Granite Harbor Agency",
        principalName: "Sean Kilbride",
        city: "Portland",
        state: "ME",
        region: "Northeast",
        appointedYear: 2009,
        premiumShare: 0.05,
        policyCount: 760,
      },
    ],
  },
  {
    slug: "cascade-specialty-risk",
    name: "Cascade Specialty Risk",
    status: MGA_STATUS.ON_PLATFORM,
    stage: DEAL_STAGE.CLOSED,
    yearsOfExperience: 26,
    foundedYear: 1999,
    principalName: "Doug Ferrante",
    headquartersCity: "Seattle",
    headquartersState: "WA",
    primaryRegion: "Pacific Northwest",
    employeeCount: 61,
    website: "cascadespecialtyrisk.com",
    acquisitionDate: "2024-02-01",
    enterpriseValueUsd: 48_000_000,
    ebitdaMultiple: 13.0,
    ownershipPercent: 82,
    dealLead: "T. Okafor",
    notes:
      "Only environmental underwriting capability on the platform. Doug's site pollution book is the single most portable product we own — it is the first candidate for transfer into the Northeast and Mid-Atlantic.",
    ebitdaMillionsByYear: [2.8, 3.1, 3.7, 4.4, 5.3],
    ebitdaMargin: 0.29,
    commissionRate: 0.148,
    programs: [
      {
        name: "Cascade Inland Marine",
        lineOfBusiness: "Inland Marine",
        coverageType: "Monoline",
        geographicRegion: "Pacific Northwest",
        carrierPartner: "Spinnaker",
        premiumWeight: 30,
        lossRatio: 0.47,
      },
      {
        name: "Pacific Environmental Liability",
        lineOfBusiness: "Environmental",
        coverageType: "Excess & Surplus",
        geographicRegion: "Pacific Northwest",
        carrierPartner: "Lloyd's Syndicate 2121",
        premiumWeight: 28,
        lossRatio: 0.55,
      },
      {
        name: "Cascade Contractors Package",
        lineOfBusiness: "General Liability",
        coverageType: "Package",
        geographicRegion: "Pacific Northwest",
        carrierPartner: "State National",
        premiumWeight: 24,
        lossRatio: 0.63,
      },
      {
        name: "Mountain West Property Binding",
        lineOfBusiness: "Commercial Property",
        coverageType: "Excess & Surplus",
        geographicRegion: "Mountain West",
        carrierPartner: "Clear Blue Specialty",
        premiumWeight: 18,
        lossRatio: 0.58,
      },
    ],
    retailAgencies: [
      {
        name: "Rainier Commercial Partners",
        principalName: "Megan Alvarez",
        city: "Tacoma",
        state: "WA",
        region: "Pacific Northwest",
        appointedYear: 2013,
        premiumShare: 0.1,
        policyCount: 1520,
      },
      {
        name: "Jake Nordstrom Agency",
        principalName: "Jake Nordstrom",
        city: "Spokane",
        state: "WA",
        region: "Pacific Northwest",
        appointedYear: 2016,
        premiumShare: 0.07,
        policyCount: 940,
      },
      {
        name: "Willamette Risk Group",
        principalName: "Curtis Pham",
        city: "Portland",
        state: "OR",
        region: "Pacific Northwest",
        appointedYear: 2012,
        premiumShare: 0.08,
        policyCount: 1130,
      },
      {
        name: "Treasure Valley Brokers",
        principalName: "Hannah Boise",
        city: "Boise",
        state: "ID",
        region: "Mountain West",
        appointedYear: 2019,
        premiumShare: 0.05,
        policyCount: 610,
      },
    ],
  },
  {
    slug: "lone-star-program-managers",
    name: "Lone Star Program Managers",
    status: MGA_STATUS.ON_PLATFORM,
    stage: DEAL_STAGE.CLOSED,
    yearsOfExperience: 33,
    foundedYear: 1992,
    principalName: "Raymond Salazar",
    headquartersCity: "Dallas",
    headquartersState: "TX",
    primaryRegion: "Texas",
    employeeCount: 132,
    website: "lonestarprograms.com",
    acquisitionDate: "2022-09-30",
    enterpriseValueUsd: 82_500_000,
    ebitdaMultiple: 14.0,
    ownershipPercent: 75,
    dealLead: "M. Ruiz",
    notes:
      "Largest MGA on the platform by premium and the anchor of the Texas presence. Commercial auto is the only trucking capability we own; loss ratios need watching at 0.71 on long-haul.",
    ebitdaMillionsByYear: [5.6, 5.9, 6.8, 7.9, 9.2],
    ebitdaMargin: 0.33,
    commissionRate: 0.14,
    programs: [
      {
        name: "Texas Commercial Trucking",
        lineOfBusiness: "Commercial Auto",
        coverageType: "Excess & Surplus",
        geographicRegion: "Texas",
        carrierPartner: "Palomar Specialty",
        premiumWeight: 36,
        lossRatio: 0.71,
      },
      {
        name: "Lone Star Workers Comp",
        lineOfBusiness: "Workers' Compensation",
        coverageType: "Admitted Primary",
        geographicRegion: "Texas",
        carrierPartner: "Accredited Specialty",
        premiumWeight: 24,
        lossRatio: 0.58,
      },
      {
        name: "Gulf Coast Energy GL",
        lineOfBusiness: "General Liability",
        coverageType: "Excess Layer",
        geographicRegion: "Gulf South",
        carrierPartner: "Everest Specialty",
        premiumWeight: 22,
        lossRatio: 0.51,
      },
      {
        name: "Border Fleet Physical Damage",
        lineOfBusiness: "Commercial Auto",
        coverageType: "Monoline",
        geographicRegion: "Texas",
        carrierPartner: "Trisura Specialty",
        premiumWeight: 18,
        lossRatio: 0.62,
      },
    ],
    retailAgencies: [
      {
        name: "Trinity Fleet Insurance Services",
        principalName: "Marcus Ibarra",
        city: "Fort Worth",
        state: "TX",
        region: "Texas",
        appointedYear: 2008,
        premiumShare: 0.11,
        policyCount: 2240,
      },
      {
        name: "Jake Bellamy & Associates",
        principalName: "Jake Bellamy",
        city: "Houston",
        state: "TX",
        region: "Texas",
        appointedYear: 2015,
        premiumShare: 0.09,
        policyCount: 1610,
      },
      {
        name: "Rio Grande Commercial Agency",
        principalName: "Sofia Trevino",
        city: "McAllen",
        state: "TX",
        region: "Texas",
        appointedYear: 2017,
        premiumShare: 0.06,
        policyCount: 980,
      },
      {
        name: "Bayou Risk Partners",
        principalName: "Lionel Guidry",
        city: "Lafayette",
        state: "LA",
        region: "Gulf South",
        appointedYear: 2020,
        premiumShare: 0.05,
        policyCount: 720,
      },
    ],
  },
  {
    slug: "meridian-casualty-group",
    name: "Meridian Casualty Group",
    status: MGA_STATUS.ON_PLATFORM,
    stage: DEAL_STAGE.CLOSED,
    yearsOfExperience: 28,
    foundedYear: 1997,
    principalName: "Gwen Ostrowski",
    headquartersCity: "Columbus",
    headquartersState: "OH",
    primaryRegion: "Midwest",
    employeeCount: 73,
    website: "meridiancasualty.com",
    acquisitionDate: "2023-11-10",
    enterpriseValueUsd: 57_500_000,
    ebitdaMultiple: 14.4,
    ownershipPercent: 80,
    dealLead: "T. Okafor",
    notes:
      "Broadest casualty capability on the platform and the second workers' comp book after Lone Star. Opened a Mid-Atlantic manufacturing program in FY25 that now overlaps Harborline's footprint.",
    ebitdaMillionsByYear: [3.4, 3.5, 4.0, 4.6, 5.5],
    ebitdaMargin: 0.28,
    commissionRate: 0.152,
    programs: [
      {
        name: "Midwest Manufacturing GL",
        lineOfBusiness: "General Liability",
        coverageType: "Package",
        geographicRegion: "Midwest",
        carrierPartner: "State National",
        premiumWeight: 30,
        lossRatio: 0.6,
      },
      {
        name: "Meridian Workers Comp",
        lineOfBusiness: "Workers' Compensation",
        coverageType: "Admitted Primary",
        geographicRegion: "Midwest",
        carrierPartner: "Accredited Specialty",
        premiumWeight: 26,
        lossRatio: 0.64,
      },
      {
        name: "Great Lakes Property Binding",
        lineOfBusiness: "Commercial Property",
        coverageType: "Excess & Surplus",
        geographicRegion: "Midwest",
        carrierPartner: "Clear Blue Specialty",
        premiumWeight: 20,
        lossRatio: 0.54,
      },
      {
        name: "Meridian Excess Casualty",
        lineOfBusiness: "General Liability",
        coverageType: "Excess Layer",
        geographicRegion: "Midwest",
        carrierPartner: "Everest Specialty",
        premiumWeight: 14,
        lossRatio: 0.42,
      },
      {
        name: "Mid-Atlantic Manufacturing GL",
        lineOfBusiness: "General Liability",
        coverageType: "Package",
        geographicRegion: "Mid-Atlantic",
        carrierPartner: "State National",
        premiumWeight: 10,
        lossRatio: 0.57,
      },
    ],
    retailAgencies: [
      {
        name: "Buckeye Commercial Group",
        principalName: "Devon Pruitt",
        city: "Columbus",
        state: "OH",
        region: "Midwest",
        appointedYear: 2010,
        premiumShare: 0.1,
        policyCount: 1480,
      },
      {
        name: "Lakeshore Insurance Advisors",
        principalName: "Jake Kowalczyk",
        city: "Chicago",
        state: "IL",
        region: "Midwest",
        appointedYear: 2014,
        premiumShare: 0.09,
        policyCount: 1350,
      },
      {
        name: "Hoosier Risk Services",
        principalName: "Amara Okonkwo",
        city: "Indianapolis",
        state: "IN",
        region: "Midwest",
        appointedYear: 2016,
        premiumShare: 0.07,
        policyCount: 1020,
      },
      {
        name: "North Star Brokers",
        principalName: "Erik Lindqvist",
        city: "Minneapolis",
        state: "MN",
        region: "Midwest",
        appointedYear: 2018,
        premiumShare: 0.06,
        policyCount: 880,
      },
      {
        name: "Keystone State Commercial",
        principalName: "Gerald Yoder",
        city: "Harrisburg",
        state: "PA",
        region: "Mid-Atlantic",
        appointedYear: 2024,
        premiumShare: 0.03,
        policyCount: 240,
      },
    ],
  },
  {
    slug: "gulf-bay-underwriters",
    name: "Gulf Bay Underwriters",
    status: MGA_STATUS.ON_PLATFORM,
    stage: DEAL_STAGE.CLOSED,
    yearsOfExperience: 24,
    foundedYear: 2001,
    principalName: "Camille Boudreaux",
    headquartersCity: "Mobile",
    headquartersState: "AL",
    primaryRegion: "Gulf South",
    employeeCount: 48,
    website: "gulfbayuw.com",
    acquisitionDate: "2025-03-20",
    enterpriseValueUsd: 51_600_000,
    ebitdaMultiple: 12.0,
    ownershipPercent: 85,
    dealLead: "M. Ruiz",
    notes:
      "Most recent close and the fastest grower on the platform at 25.2%, driven by coastal wind rate. Overlaps Lone Star in both Texas and the Gulf South, which is the clearest consolidation opportunity we own.",
    ebitdaMillionsByYear: [2.2, 2.9, 3.5, 4.3, 5.4],
    ebitdaMargin: 0.3,
    commissionRate: 0.16,
    programs: [
      {
        name: "Coastal Wind & Hail",
        lineOfBusiness: "Commercial Property",
        coverageType: "Excess & Surplus",
        geographicRegion: "Gulf South",
        carrierPartner: "Lloyd's Syndicate 2121",
        premiumWeight: 36,
        lossRatio: 0.57,
      },
      {
        name: "Gulf Marine Cargo",
        lineOfBusiness: "Inland Marine",
        coverageType: "Monoline",
        geographicRegion: "Gulf South",
        carrierPartner: "Spinnaker",
        premiumWeight: 22,
        lossRatio: 0.45,
      },
      {
        name: "Southeast Habitational Property",
        lineOfBusiness: "Commercial Property",
        coverageType: "Excess Layer",
        geographicRegion: "Southeast",
        carrierPartner: "Palomar Specialty",
        premiumWeight: 20,
        lossRatio: 0.61,
      },
      {
        name: "Gulf Bay Contractors GL",
        lineOfBusiness: "General Liability",
        coverageType: "Admitted Primary",
        geographicRegion: "Gulf South",
        carrierPartner: "Trisura Specialty",
        premiumWeight: 12,
        lossRatio: 0.59,
      },
      {
        name: "Texas Coastal Property",
        lineOfBusiness: "Commercial Property",
        coverageType: "Excess & Surplus",
        geographicRegion: "Texas",
        carrierPartner: "Palomar Specialty",
        premiumWeight: 10,
        lossRatio: 0.64,
      },
    ],
    retailAgencies: [
      {
        name: "Azalea Coast Insurance",
        principalName: "Tobias Fairchild",
        city: "Mobile",
        state: "AL",
        region: "Gulf South",
        appointedYear: 2012,
        premiumShare: 0.12,
        policyCount: 1290,
      },
      {
        name: "Jake Rousseau Agency",
        principalName: "Jake Rousseau",
        city: "New Orleans",
        state: "LA",
        region: "Gulf South",
        appointedYear: 2015,
        premiumShare: 0.09,
        policyCount: 1040,
      },
      {
        name: "Emerald Coast Brokers",
        principalName: "Denise Whitaker",
        city: "Pensacola",
        state: "FL",
        region: "Southeast",
        appointedYear: 2017,
        premiumShare: 0.08,
        policyCount: 910,
      },
      {
        name: "Lowcountry Risk Advisors",
        principalName: "Garrett Mabry",
        city: "Charleston",
        state: "SC",
        region: "Southeast",
        appointedYear: 2021,
        premiumShare: 0.05,
        policyCount: 540,
      },
    ],
  },
  {
    slug: "summit-professional-lines",
    name: "Summit Professional Lines",
    status: MGA_STATUS.ON_PLATFORM,
    stage: DEAL_STAGE.CLOSED,
    yearsOfExperience: 22,
    foundedYear: 2003,
    principalName: "Nadia Farouk",
    headquartersCity: "Denver",
    headquartersState: "CO",
    primaryRegion: "Mountain West",
    employeeCount: 39,
    website: "summitprolines.com",
    acquisitionDate: "2024-08-05",
    enterpriseValueUsd: 45_600_000,
    ebitdaMultiple: 15.2,
    ownershipPercent: 79,
    dealLead: "T. Okafor",
    notes:
      "Highest multiple paid on the platform, justified by 25.4% growth and the only professional lines and cyber capability we own. Both products are nationally filed and unattached to any region.",
    ebitdaMillionsByYear: [1.9, 2.4, 3.0, 3.8, 4.7],
    ebitdaMargin: 0.34,
    commissionRate: 0.18,
    programs: [
      {
        name: "Summit Miscellaneous Professional",
        lineOfBusiness: "Professional Liability",
        coverageType: "Excess & Surplus",
        geographicRegion: "Mountain West",
        carrierPartner: "Trisura Specialty",
        premiumWeight: 30,
        lossRatio: 0.48,
      },
      {
        name: "Allied Health E&O",
        lineOfBusiness: "Professional Liability",
        coverageType: "Program Business",
        geographicRegion: "Nationwide",
        carrierPartner: "Everest Specialty",
        premiumWeight: 26,
        lossRatio: 0.52,
      },
      {
        name: "Summit Cyber Managers",
        lineOfBusiness: "Cyber",
        coverageType: "Excess & Surplus",
        geographicRegion: "Nationwide",
        carrierPartner: "Lloyd's Syndicate 2121",
        premiumWeight: 22,
        lossRatio: 0.39,
      },
      {
        name: "Front Range Tech E&O",
        lineOfBusiness: "Professional Liability",
        coverageType: "Monoline",
        geographicRegion: "Mountain West",
        carrierPartner: "Accredited Specialty",
        premiumWeight: 12,
        lossRatio: 0.44,
      },
      {
        name: "Pacific Professional Lines",
        lineOfBusiness: "Professional Liability",
        coverageType: "Excess & Surplus",
        geographicRegion: "Pacific Northwest",
        carrierPartner: "Trisura Specialty",
        premiumWeight: 10,
        lossRatio: 0.46,
      },
    ],
    retailAgencies: [
      {
        name: "Mile High Professional Risk",
        principalName: "Bianca Delgado",
        city: "Denver",
        state: "CO",
        region: "Mountain West",
        appointedYear: 2013,
        premiumShare: 0.11,
        policyCount: 830,
      },
      {
        name: "Wasatch Advisory Group",
        principalName: "Jake Pemberton",
        city: "Salt Lake City",
        state: "UT",
        region: "Mountain West",
        appointedYear: 2017,
        premiumShare: 0.08,
        policyCount: 640,
      },
      {
        name: "Desert Ridge Insurance",
        principalName: "Omar Haddad",
        city: "Phoenix",
        state: "AZ",
        region: "Mountain West",
        appointedYear: 2019,
        premiumShare: 0.07,
        policyCount: 520,
      },
      {
        name: "Bay Area Specialty Brokers",
        principalName: "Lillian Chow",
        city: "San Jose",
        state: "CA",
        region: "California",
        appointedYear: 2022,
        premiumShare: 0.06,
        policyCount: 410,
      },
    ],
  },

  // ---------------------------------------------------------------------------
  // Pipeline
  // ---------------------------------------------------------------------------
  {
    slug: "keystone-environmental-partners",
    name: "Keystone Environmental Partners",
    status: MGA_STATUS.PIPELINE,
    stage: DEAL_STAGE.DILIGENCE,
    yearsOfExperience: 27,
    foundedYear: 1998,
    principalName: "Walter Hennessey",
    headquartersCity: "Pittsburgh",
    headquartersState: "PA",
    primaryRegion: "Mid-Atlantic",
    employeeCount: 54,
    website: "keystoneenviro.com",
    ebitdaMultiple: 13.0,
    dealLead: "T. Okafor",
    notes:
      "Top-ranked target. Clears all three thesis criteria and doubles the platform's environmental capability into the Mid-Atlantic, which Cascade cannot reach. Quality of earnings started 8 September.",
    ebitdaMillionsByYear: [2.6, 3.2, 4.1, 5.0, 6.2],
    projectedEbitdaMillions: 7.4,
    ebitdaMargin: 0.32,
    commissionRate: 0.15,
    programs: [
      {
        name: "Keystone Site Pollution Legal Liability",
        lineOfBusiness: "Environmental",
        coverageType: "Excess & Surplus",
        geographicRegion: "Mid-Atlantic",
        carrierPartner: "Lloyd's Syndicate 2121",
        premiumWeight: 38,
        lossRatio: 0.46,
      },
      {
        name: "Contractors Pollution",
        lineOfBusiness: "Environmental",
        coverageType: "Package",
        geographicRegion: "Mid-Atlantic",
        carrierPartner: "State National",
        premiumWeight: 26,
        lossRatio: 0.53,
      },
      {
        name: "Northeast Storage Tank Program",
        lineOfBusiness: "Environmental",
        coverageType: "Program Business",
        geographicRegion: "Northeast",
        carrierPartner: "Clear Blue Specialty",
        premiumWeight: 22,
        lossRatio: 0.49,
      },
      {
        name: "Keystone Excess Environmental",
        lineOfBusiness: "Environmental",
        coverageType: "Excess Layer",
        geographicRegion: "Mid-Atlantic",
        carrierPartner: "Everest Specialty",
        premiumWeight: 14,
        lossRatio: 0.38,
      },
    ],
    retailAgencies: [
      {
        name: "Three Rivers Environmental Brokers",
        principalName: "Nolan Petrusich",
        city: "Pittsburgh",
        state: "PA",
        region: "Mid-Atlantic",
        appointedYear: 2011,
        premiumShare: 0.12,
        policyCount: 690,
      },
      {
        name: "Chesapeake Risk Group",
        principalName: "Yolanda Mercer",
        city: "Baltimore",
        state: "MD",
        region: "Mid-Atlantic",
        appointedYear: 2015,
        premiumShare: 0.09,
        policyCount: 540,
      },
      {
        name: "Jake Sutherland Insurance",
        principalName: "Jake Sutherland",
        city: "Newark",
        state: "NJ",
        region: "Northeast",
        appointedYear: 2018,
        premiumShare: 0.07,
        policyCount: 430,
      },
    ],
  },
  {
    slug: "beacon-hill-specialty",
    name: "Beacon Hill Specialty",
    status: MGA_STATUS.PIPELINE,
    stage: DEAL_STAGE.UNDER_LOI,
    yearsOfExperience: 30,
    foundedYear: 1995,
    principalName: "Frederick Alcott",
    headquartersCity: "Boston",
    headquartersState: "MA",
    primaryRegion: "Northeast",
    employeeCount: 66,
    website: "beaconhillspecialty.com",
    ebitdaMultiple: 14.5,
    dealLead: "M. Ruiz",
    notes:
      "LOI signed at 14.5x. Thirty-year operator, and the lawyers professional book would give Summit's professional lines capability a Northeast home. Exclusivity runs to 30 October.",
    ebitdaMillionsByYear: [3.8, 4.3, 5.1, 6.0, 7.1],
    projectedEbitdaMillions: 8.2,
    ebitdaMargin: 0.35,
    commissionRate: 0.165,
    programs: [
      {
        name: "Beacon Hill Lawyers Professional",
        lineOfBusiness: "Professional Liability",
        coverageType: "Program Business",
        geographicRegion: "Northeast",
        carrierPartner: "Trisura Specialty",
        premiumWeight: 34,
        lossRatio: 0.44,
      },
      {
        name: "New England D&O",
        lineOfBusiness: "Professional Liability",
        coverageType: "Excess & Surplus",
        geographicRegion: "Northeast",
        carrierPartner: "Everest Specialty",
        premiumWeight: 28,
        lossRatio: 0.41,
      },
      {
        name: "Beacon Cyber Liability",
        lineOfBusiness: "Cyber",
        coverageType: "Monoline",
        geographicRegion: "Northeast",
        carrierPartner: "Lloyd's Syndicate 2121",
        premiumWeight: 22,
        lossRatio: 0.36,
      },
      {
        name: "Mid-Atlantic Miscellaneous E&O",
        lineOfBusiness: "Professional Liability",
        coverageType: "Excess Layer",
        geographicRegion: "Mid-Atlantic",
        carrierPartner: "Accredited Specialty",
        premiumWeight: 16,
        lossRatio: 0.47,
      },
    ],
    retailAgencies: [
      {
        name: "Back Bay Professional Risk",
        principalName: "Imogen Clarke",
        city: "Boston",
        state: "MA",
        region: "Northeast",
        appointedYear: 2009,
        premiumShare: 0.11,
        policyCount: 720,
      },
      {
        name: "Nutmeg Advisory Partners",
        principalName: "Roland Vasquez",
        city: "Hartford",
        state: "CT",
        region: "Northeast",
        appointedYear: 2014,
        premiumShare: 0.08,
        policyCount: 560,
      },
      {
        name: "Empire State E&O Brokers",
        principalName: "Jake Moretti",
        city: "New York",
        state: "NY",
        region: "Northeast",
        appointedYear: 2016,
        premiumShare: 0.1,
        policyCount: 810,
      },
    ],
  },
  {
    slug: "sierra-crest-underwriters",
    name: "Sierra Crest Underwriters",
    status: MGA_STATUS.PIPELINE,
    stage: DEAL_STAGE.QUALIFIED,
    yearsOfExperience: 21,
    foundedYear: 2004,
    principalName: "Hector Villanueva",
    headquartersCity: "Sacramento",
    headquartersState: "CA",
    primaryRegion: "California",
    employeeCount: 44,
    website: "sierracrestuw.com",
    ebitdaMultiple: 12.5,
    dealLead: "T. Okafor",
    notes:
      "Only California entry point in the pipeline. 27.3% growth is real but wildfire-driven; the 0.68 loss ratio on the wildfire book is the central diligence question.",
    ebitdaMillionsByYear: [1.6, 2.1, 2.7, 3.4, 4.2],
    projectedEbitdaMillions: 5.0,
    ebitdaMargin: 0.29,
    commissionRate: 0.155,
    programs: [
      {
        name: "Sierra Wildfire Property",
        lineOfBusiness: "Commercial Property",
        coverageType: "Excess & Surplus",
        geographicRegion: "California",
        carrierPartner: "Palomar Specialty",
        premiumWeight: 40,
        lossRatio: 0.68,
      },
      {
        name: "California Habitational Package",
        lineOfBusiness: "Commercial Property",
        coverageType: "Package",
        geographicRegion: "California",
        carrierPartner: "Clear Blue Specialty",
        premiumWeight: 26,
        lossRatio: 0.59,
      },
      {
        name: "Sierra Contractors GL",
        lineOfBusiness: "General Liability",
        coverageType: "Admitted Primary",
        geographicRegion: "California",
        carrierPartner: "State National",
        premiumWeight: 20,
        lossRatio: 0.62,
      },
      {
        name: "Pacific Excess Property",
        lineOfBusiness: "Commercial Property",
        coverageType: "Excess Layer",
        geographicRegion: "Pacific Northwest",
        carrierPartner: "Everest Specialty",
        premiumWeight: 14,
        lossRatio: 0.5,
      },
    ],
    retailAgencies: [
      {
        name: "Golden Valley Insurance Group",
        principalName: "Priscilla Nakamura",
        city: "Sacramento",
        state: "CA",
        region: "California",
        appointedYear: 2012,
        premiumShare: 0.12,
        policyCount: 1340,
      },
      {
        name: "Jake Ferreira Agency",
        principalName: "Jake Ferreira",
        city: "Fresno",
        state: "CA",
        region: "California",
        appointedYear: 2016,
        premiumShare: 0.09,
        policyCount: 980,
      },
      {
        name: "Cascadia Property Brokers",
        principalName: "Trent Halvorsen",
        city: "Eugene",
        state: "OR",
        region: "Pacific Northwest",
        appointedYear: 2020,
        premiumShare: 0.06,
        policyCount: 470,
      },
    ],
  },
  {
    slug: "atlantic-surety-group",
    name: "Atlantic Surety Group",
    status: MGA_STATUS.PIPELINE,
    stage: DEAL_STAGE.SOURCED,
    yearsOfExperience: 25,
    foundedYear: 2000,
    principalName: "Della Ruffin",
    headquartersCity: "Charlotte",
    headquartersState: "NC",
    primaryRegion: "Southeast",
    employeeCount: 27,
    website: "atlanticsurety.com",
    ebitdaMultiple: 11.5,
    dealLead: "M. Ruiz",
    notes:
      "Cheapest asset in the pipeline at 11.5x and the lowest loss ratios we have seen anywhere at 0.24 to 0.31. Surety is a capability the platform does not own at all.",
    ebitdaMillionsByYear: [2.0, 2.2, 2.5, 2.9, 3.4],
    projectedEbitdaMillions: 3.8,
    ebitdaMargin: 0.36,
    commissionRate: 0.2,
    programs: [
      {
        name: "Contract Surety Program",
        lineOfBusiness: "Surety",
        coverageType: "Program Business",
        geographicRegion: "Southeast",
        carrierPartner: "Accredited Specialty",
        premiumWeight: 46,
        lossRatio: 0.28,
      },
      {
        name: "Commercial Surety Bonds",
        lineOfBusiness: "Surety",
        coverageType: "Monoline",
        geographicRegion: "Southeast",
        carrierPartner: "Trisura Specialty",
        premiumWeight: 32,
        lossRatio: 0.24,
      },
      {
        name: "Mid-Atlantic Contractor Bonds",
        lineOfBusiness: "Surety",
        coverageType: "Program Business",
        geographicRegion: "Mid-Atlantic",
        carrierPartner: "Everest Specialty",
        premiumWeight: 22,
        lossRatio: 0.31,
      },
    ],
    retailAgencies: [
      {
        name: "Queen City Bonding",
        principalName: "Marcus Threadgill",
        city: "Charlotte",
        state: "NC",
        region: "Southeast",
        appointedYear: 2013,
        premiumShare: 0.14,
        policyCount: 520,
      },
      {
        name: "Peachtree Surety Advisors",
        principalName: "Nia Boseman",
        city: "Atlanta",
        state: "GA",
        region: "Southeast",
        appointedYear: 2017,
        premiumShare: 0.11,
        policyCount: 410,
      },
      {
        name: "Jake Ellington Bond Brokers",
        principalName: "Jake Ellington",
        city: "Norfolk",
        state: "VA",
        region: "Mid-Atlantic",
        appointedYear: 2019,
        premiumShare: 0.08,
        policyCount: 300,
      },
    ],
  },
  {
    slug: "great-lakes-transport-risk",
    name: "Great Lakes Transport Risk",
    status: MGA_STATUS.PIPELINE,
    stage: DEAL_STAGE.DILIGENCE,
    yearsOfExperience: 32,
    foundedYear: 1993,
    principalName: "Stan Kowalski",
    headquartersCity: "Detroit",
    headquartersState: "MI",
    primaryRegion: "Midwest",
    employeeCount: 98,
    website: "greatlakestransportrisk.com",
    ebitdaMultiple: 10.5,
    dealLead: "T. Okafor",
    notes:
      "Misses the 12% growth screen at 11.9% because of the FY22 rate correction, and is the largest pipeline asset by premium. Worth an explicit board decision rather than a filter — on a three-year basis it compounds at 18.6%.",
    ebitdaMillionsByYear: [4.4, 4.2, 4.9, 5.8, 6.9],
    projectedEbitdaMillions: 7.7,
    ebitdaMargin: 0.27,
    commissionRate: 0.13,
    programs: [
      {
        name: "Great Lakes Long-Haul Trucking",
        lineOfBusiness: "Commercial Auto",
        coverageType: "Excess & Surplus",
        geographicRegion: "Midwest",
        carrierPartner: "Palomar Specialty",
        premiumWeight: 42,
        lossRatio: 0.71,
      },
      {
        name: "Regional Fleet Package",
        lineOfBusiness: "Commercial Auto",
        coverageType: "Package",
        geographicRegion: "Midwest",
        carrierPartner: "State National",
        premiumWeight: 26,
        lossRatio: 0.65,
      },
      {
        name: "Motor Truck Cargo",
        lineOfBusiness: "Inland Marine",
        coverageType: "Monoline",
        geographicRegion: "Midwest",
        carrierPartner: "Spinnaker",
        premiumWeight: 20,
        lossRatio: 0.48,
      },
      {
        name: "Transport Excess Liability",
        lineOfBusiness: "Commercial Auto",
        coverageType: "Excess Layer",
        geographicRegion: "Midwest",
        carrierPartner: "Everest Specialty",
        premiumWeight: 12,
        lossRatio: 0.55,
      },
    ],
    retailAgencies: [
      {
        name: "Motor City Fleet Insurance",
        principalName: "Reuben Saltzman",
        city: "Detroit",
        state: "MI",
        region: "Midwest",
        appointedYear: 2007,
        premiumShare: 0.13,
        policyCount: 1920,
      },
      {
        name: "Jake Vandermolen Agency",
        principalName: "Jake Vandermolen",
        city: "Grand Rapids",
        state: "MI",
        region: "Midwest",
        appointedYear: 2014,
        premiumShare: 0.09,
        policyCount: 1310,
      },
      {
        name: "Steel Valley Transport Brokers",
        principalName: "Camila Restrepo",
        city: "Cleveland",
        state: "OH",
        region: "Midwest",
        appointedYear: 2018,
        premiumShare: 0.07,
        policyCount: 1050,
      },
    ],
  },
  {
    slug: "palmetto-coastal-underwriters",
    name: "Palmetto Coastal Underwriters",
    status: MGA_STATUS.PIPELINE,
    stage: DEAL_STAGE.QUALIFIED,
    yearsOfExperience: 19,
    foundedYear: 2006,
    principalName: "Beau Ravenel",
    headquartersCity: "Charleston",
    headquartersState: "SC",
    primaryRegion: "Southeast",
    employeeCount: 33,
    website: "palmettocoastaluw.com",
    ebitdaMultiple: 12.0,
    dealLead: "M. Ruiz",
    notes:
      "Fastest grower in the pipeline at 30.8%, but Beau founded the agency in 2006 — nineteen years, one short of thesis. Flagged rather than hidden so the board decides deliberately.",
    ebitdaMillionsByYear: [1.4, 1.9, 2.6, 3.3, 4.1],
    projectedEbitdaMillions: 4.9,
    ebitdaMargin: 0.31,
    commissionRate: 0.165,
    programs: [
      {
        name: "Palmetto Coastal Property",
        lineOfBusiness: "Commercial Property",
        coverageType: "Excess & Surplus",
        geographicRegion: "Southeast",
        carrierPartner: "Palomar Specialty",
        premiumWeight: 44,
        lossRatio: 0.63,
      },
      {
        name: "Lowcountry Habitational",
        lineOfBusiness: "Commercial Property",
        coverageType: "Package",
        geographicRegion: "Southeast",
        carrierPartner: "Clear Blue Specialty",
        premiumWeight: 26,
        lossRatio: 0.58,
      },
      {
        name: "Coastal Marine Program",
        lineOfBusiness: "Inland Marine",
        coverageType: "Program Business",
        geographicRegion: "Southeast",
        carrierPartner: "Spinnaker",
        premiumWeight: 18,
        lossRatio: 0.44,
      },
      {
        name: "Gulf Excess Property",
        lineOfBusiness: "Commercial Property",
        coverageType: "Excess Layer",
        geographicRegion: "Gulf South",
        carrierPartner: "Everest Specialty",
        premiumWeight: 12,
        lossRatio: 0.66,
      },
    ],
    retailAgencies: [
      {
        name: "Ravenel & Hayes Insurance",
        principalName: "Sutton Hayes",
        city: "Charleston",
        state: "SC",
        region: "Southeast",
        appointedYear: 2010,
        premiumShare: 0.13,
        policyCount: 640,
      },
      {
        name: "Jake Calloway Insurance",
        principalName: "Jake Calloway",
        city: "Savannah",
        state: "GA",
        region: "Southeast",
        appointedYear: 2015,
        premiumShare: 0.1,
        policyCount: 480,
      },
      {
        name: "Panhandle Coastal Brokers",
        principalName: "Rosalind Kemp",
        city: "Panama City",
        state: "FL",
        region: "Gulf South",
        appointedYear: 2021,
        premiumShare: 0.06,
        policyCount: 290,
      },
    ],
  },
  {
    slug: "front-range-cyber-managers",
    name: "Front Range Cyber Managers",
    status: MGA_STATUS.PIPELINE,
    stage: DEAL_STAGE.SOURCED,
    yearsOfExperience: 8,
    foundedYear: 2017,
    principalName: "Priya Venkataraman",
    headquartersCity: "Boulder",
    headquartersState: "CO",
    primaryRegion: "Mountain West",
    employeeCount: 22,
    website: "frontrangecyber.com",
    ebitdaMultiple: 16.0,
    dealLead: "T. Okafor",
    notes:
      "56.5% EBITDA CAGR and the only standalone cyber MGA we have seen at this size, against eight years of operating history. Fails the tenure screen by design; surfaced so the exception is deliberate.",
    ebitdaMillionsByYear: [0.6, 1.1, 1.8, 2.6, 3.6],
    projectedEbitdaMillions: 4.8,
    ebitdaMargin: 0.38,
    commissionRate: 0.19,
    programs: [
      {
        name: "Front Range SMB Cyber",
        lineOfBusiness: "Cyber",
        coverageType: "Program Business",
        geographicRegion: "Nationwide",
        carrierPartner: "Lloyd's Syndicate 2121",
        premiumWeight: 52,
        lossRatio: 0.34,
      },
      {
        name: "Tech E&O Plus Cyber",
        lineOfBusiness: "Cyber",
        coverageType: "Package",
        geographicRegion: "Mountain West",
        carrierPartner: "Trisura Specialty",
        premiumWeight: 30,
        lossRatio: 0.4,
      },
      {
        name: "Cyber Excess Tower",
        lineOfBusiness: "Cyber",
        coverageType: "Excess Layer",
        geographicRegion: "Nationwide",
        carrierPartner: "Everest Specialty",
        premiumWeight: 18,
        lossRatio: 0.29,
      },
    ],
    retailAgencies: [
      {
        name: "Flatirons Technology Insurance",
        principalName: "Grant Wiedemann",
        city: "Boulder",
        state: "CO",
        region: "Mountain West",
        appointedYear: 2018,
        premiumShare: 0.15,
        policyCount: 380,
      },
      {
        name: "Jake Okafor Digital Risk",
        principalName: "Jake Okafor",
        city: "Austin",
        state: "TX",
        region: "Texas",
        appointedYear: 2020,
        premiumShare: 0.11,
        policyCount: 260,
      },
      {
        name: "Silicon Slopes Brokers",
        principalName: "Tessa Holbrook",
        city: "Provo",
        state: "UT",
        region: "Mountain West",
        appointedYear: 2021,
        premiumShare: 0.09,
        policyCount: 210,
      },
    ],
  },
  {
    slug: "brazos-valley-agribusiness",
    name: "Brazos Valley Agribusiness",
    status: MGA_STATUS.PIPELINE,
    stage: DEAL_STAGE.QUALIFIED,
    yearsOfExperience: 36,
    foundedYear: 1989,
    principalName: "Delbert Krauss",
    headquartersCity: "Waco",
    headquartersState: "TX",
    primaryRegion: "Texas",
    employeeCount: 51,
    website: "brazosvalleyag.com",
    ebitdaMultiple: 11.0,
    dealLead: "M. Ruiz",
    notes:
      "Longest-tenured operator we have looked at, 36 years. Clears all three criteria and would deepen Texas alongside Lone Star, though succession is the open question — Delbert is 68 with no named successor.",
    ebitdaMillionsByYear: [2.9, 3.1, 3.6, 4.2, 4.9],
    projectedEbitdaMillions: 5.4,
    ebitdaMargin: 0.3,
    commissionRate: 0.145,
    programs: [
      {
        name: "Brazos Farm & Ranch Package",
        lineOfBusiness: "Commercial Property",
        coverageType: "Package",
        geographicRegion: "Texas",
        carrierPartner: "State National",
        premiumWeight: 38,
        lossRatio: 0.6,
      },
      {
        name: "Agribusiness Equipment Marine",
        lineOfBusiness: "Inland Marine",
        coverageType: "Monoline",
        geographicRegion: "Texas",
        carrierPartner: "Spinnaker",
        premiumWeight: 24,
        lossRatio: 0.46,
      },
      {
        name: "Agricultural Workers Comp",
        lineOfBusiness: "Workers' Compensation",
        coverageType: "Program Business",
        geographicRegion: "Texas",
        carrierPartner: "Accredited Specialty",
        premiumWeight: 22,
        lossRatio: 0.67,
      },
      {
        name: "Gulf South Crop Liability",
        lineOfBusiness: "General Liability",
        coverageType: "Admitted Primary",
        geographicRegion: "Gulf South",
        carrierPartner: "Trisura Specialty",
        premiumWeight: 16,
        lossRatio: 0.57,
      },
    ],
    retailAgencies: [
      {
        name: "Heart of Texas Agency",
        principalName: "Odell Barnhart",
        city: "Waco",
        state: "TX",
        region: "Texas",
        appointedYear: 2009,
        premiumShare: 0.12,
        policyCount: 1140,
      },
      {
        name: "Panhandle Ag Insurance",
        principalName: "Juanita Escobar",
        city: "Amarillo",
        state: "TX",
        region: "Texas",
        appointedYear: 2014,
        premiumShare: 0.09,
        policyCount: 870,
      },
      {
        name: "Jake Thibodeaux Agency",
        principalName: "Jake Thibodeaux",
        city: "Lake Charles",
        state: "LA",
        region: "Gulf South",
        appointedYear: 2018,
        premiumShare: 0.07,
        policyCount: 560,
      },
    ],
  },
  {
    slug: "noreaster-marine-underwriters",
    name: "Nor'easter Marine Underwriters",
    status: MGA_STATUS.PIPELINE,
    stage: DEAL_STAGE.UNDER_LOI,
    yearsOfExperience: 29,
    foundedYear: 1996,
    principalName: "Colm Brannigan",
    headquartersCity: "Providence",
    headquartersState: "RI",
    primaryRegion: "Northeast",
    employeeCount: 31,
    website: "noreastermarine.com",
    ebitdaMultiple: 13.5,
    dealLead: "M. Ruiz",
    notes:
      "LOI signed. Third inland marine book on the platform after Cascade and Gulf Bay, which makes a consolidated marine practice across three coasts a real option rather than a slide.",
    ebitdaMillionsByYear: [1.8, 2.2, 2.7, 3.2, 3.9],
    projectedEbitdaMillions: 4.4,
    ebitdaMargin: 0.33,
    commissionRate: 0.17,
    programs: [
      {
        name: "Nor'easter Yacht & Marina",
        lineOfBusiness: "Inland Marine",
        coverageType: "Program Business",
        geographicRegion: "Northeast",
        carrierPartner: "Spinnaker",
        premiumWeight: 40,
        lossRatio: 0.49,
      },
      {
        name: "Commercial Hull & Cargo",
        lineOfBusiness: "Inland Marine",
        coverageType: "Excess & Surplus",
        geographicRegion: "Northeast",
        carrierPartner: "Lloyd's Syndicate 2121",
        premiumWeight: 28,
        lossRatio: 0.52,
      },
      {
        name: "Marina Operators Liability",
        lineOfBusiness: "General Liability",
        coverageType: "Package",
        geographicRegion: "Northeast",
        carrierPartner: "Clear Blue Specialty",
        premiumWeight: 20,
        lossRatio: 0.55,
      },
      {
        name: "Mid-Atlantic Marine Cargo",
        lineOfBusiness: "Inland Marine",
        coverageType: "Monoline",
        geographicRegion: "Mid-Atlantic",
        carrierPartner: "Trisura Specialty",
        premiumWeight: 12,
        lossRatio: 0.43,
      },
    ],
    retailAgencies: [
      {
        name: "Narragansett Marine Insurance",
        principalName: "Fiona Mulcahy",
        city: "Providence",
        state: "RI",
        region: "Northeast",
        appointedYear: 2011,
        premiumShare: 0.13,
        policyCount: 590,
      },
      {
        name: "Jake Petrosian Agency",
        principalName: "Jake Petrosian",
        city: "Greenwich",
        state: "CT",
        region: "Northeast",
        appointedYear: 2016,
        premiumShare: 0.1,
        policyCount: 470,
      },
      {
        name: "Annapolis Yacht Risk",
        principalName: "Bernard Quillen",
        city: "Annapolis",
        state: "MD",
        region: "Mid-Atlantic",
        appointedYear: 2019,
        premiumShare: 0.07,
        policyCount: 330,
      },
    ],
  },
  {
    slug: "old-dominion-general-lines",
    name: "Old Dominion General Lines",
    status: MGA_STATUS.PIPELINE,
    stage: DEAL_STAGE.SOURCED,
    yearsOfExperience: 34,
    foundedYear: 1991,
    principalName: "Hollis Tazewell",
    headquartersCity: "Richmond",
    headquartersState: "VA",
    primaryRegion: "Mid-Atlantic",
    employeeCount: 77,
    website: "olddominiongl.com",
    ebitdaMultiple: 8.5,
    dealLead: "T. Okafor",
    notes:
      "Thirty-four years of history and clean loss ratios, but EBITDA has sat at roughly $3.6M since FY21 — a 1.4% CAGR against a 12% thesis. Tenure and scale clear; growth does not.",
    ebitdaMillionsByYear: [3.6, 3.5, 3.6, 3.7, 3.8],
    projectedEbitdaMillions: 3.9,
    ebitdaMargin: 0.26,
    commissionRate: 0.14,
    programs: [
      {
        name: "Old Dominion Contractors GL",
        lineOfBusiness: "General Liability",
        coverageType: "Admitted Primary",
        geographicRegion: "Mid-Atlantic",
        carrierPartner: "State National",
        premiumWeight: 36,
        lossRatio: 0.62,
      },
      {
        name: "Virginia Small Commercial Package",
        lineOfBusiness: "General Liability",
        coverageType: "Package",
        geographicRegion: "Mid-Atlantic",
        carrierPartner: "Clear Blue Specialty",
        premiumWeight: 30,
        lossRatio: 0.64,
      },
      {
        name: "Mid-Atlantic Property Monoline",
        lineOfBusiness: "Commercial Property",
        coverageType: "Monoline",
        geographicRegion: "Mid-Atlantic",
        carrierPartner: "Accredited Specialty",
        premiumWeight: 22,
        lossRatio: 0.58,
      },
      {
        name: "Southeast Excess Casualty",
        lineOfBusiness: "General Liability",
        coverageType: "Excess Layer",
        geographicRegion: "Southeast",
        carrierPartner: "Everest Specialty",
        premiumWeight: 12,
        lossRatio: 0.49,
      },
    ],
    retailAgencies: [
      {
        name: "Shenandoah Insurance Advisors",
        principalName: "Warren Beckley",
        city: "Roanoke",
        state: "VA",
        region: "Mid-Atlantic",
        appointedYear: 2008,
        premiumShare: 0.11,
        policyCount: 1280,
      },
      {
        name: "Jake Harrelson Agency",
        principalName: "Jake Harrelson",
        city: "Richmond",
        state: "VA",
        region: "Mid-Atlantic",
        appointedYear: 2013,
        premiumShare: 0.09,
        policyCount: 1010,
      },
      {
        name: "Research Triangle Brokers",
        principalName: "Simone Ashby",
        city: "Raleigh",
        state: "NC",
        region: "Southeast",
        appointedYear: 2017,
        premiumShare: 0.06,
        policyCount: 690,
      },
    ],
  },
  {
    slug: "cardinal-workers-comp-specialists",
    name: "Cardinal Workers Comp Specialists",
    status: MGA_STATUS.PIPELINE,
    stage: DEAL_STAGE.PASSED,
    yearsOfExperience: 23,
    foundedYear: 2002,
    principalName: "Vince Mazzola",
    headquartersCity: "St. Louis",
    headquartersState: "MO",
    primaryRegion: "Midwest",
    employeeCount: 29,
    website: "cardinalwc.com",
    dealLead: "T. Okafor",
    notes:
      "Passed in Q1. Missouri comp rates have fallen four years running, EBITDA is down 10.1% a year, and the book overlaps Meridian's comp program without adding a region. Kept in the system so the reasoning survives the next time it is offered.",
    ebitdaMillionsByYear: [2.6, 2.4, 2.2, 2.0, 1.7],
    ebitdaMargin: 0.24,
    commissionRate: 0.145,
    programs: [
      {
        name: "Missouri Comp Program",
        lineOfBusiness: "Workers' Compensation",
        coverageType: "Program Business",
        geographicRegion: "Midwest",
        carrierPartner: "Accredited Specialty",
        premiumWeight: 62,
        lossRatio: 0.78,
      },
      {
        name: "Midwest Comp Excess",
        lineOfBusiness: "Workers' Compensation",
        coverageType: "Excess Layer",
        geographicRegion: "Midwest",
        carrierPartner: "Everest Specialty",
        premiumWeight: 38,
        lossRatio: 0.61,
      },
    ],
    retailAgencies: [
      {
        name: "Gateway Comp Advisors",
        principalName: "Lucinda Harkness",
        city: "St. Louis",
        state: "MO",
        region: "Midwest",
        appointedYear: 2012,
        premiumShare: 0.16,
        policyCount: 740,
      },
      {
        name: "Ozark Risk Group",
        principalName: "Dwight Faber",
        city: "Springfield",
        state: "MO",
        region: "Midwest",
        appointedYear: 2016,
        premiumShare: 0.12,
        policyCount: 520,
      },
    ],
  },
];
